name: Deploy svelte project to gh pages
run-name: Triggered by @${{github.actor}}
on:
  push:
    branches: [ 'main' ]
permissions:
  id-token: write
  pages: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Build release version
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to gh pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
          artifact_name: build