name: Deploy svelte project to gh pages
run-name: Triggered by @${{github.actor}}
on:
  push:
    branches: [ 'main' ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 18
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Build release version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Deploy to gh pages
        uses: actions/deploy-pages@v2