name: Deploy svelte project to gh pages
run-name: Triggered by @${{github.actor}}
on:
  push:
    branches: [ 'main' ]
permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - name: Build release version
        run: npm run build
      - name: Deploy to gh pages
        uses: actions/deploy-pages@v2